-- vim: set ts=4 sw=4 noet:

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

require("functions")

chassis_type = system("hostnamectl chassis")

if chassis_type == "desktop" then
	local superwide = "DP-1"
	local top_left = "DP-3"
	local top_right = "DP-5"

	hl.monitor({
		-- output = "desc:Dell Inc. DELL U4025QW 35QP934",
		output = superwide,
		position = "0x1440",
		--position = 0x0
		mode = "5120x2160@60",
		scale = "1",
		vrr = false,
		-- bitdepth = 10
		-- cm = hdredid
		-- sdrbrightness = 1.0
		-- sdrsaturation = 1.15
		-- sdr_min_luminance = 0.005
		-- sdr_max_luminance = 350
	})

	hl.monitor({
		output = top_left,
		disabled = false,
		mode = "2560x1440@60",
		position = "0x0",
		scale = "1",
	})

	hl.monitor({
		output = top_right,
		disabled = false,
		mode = "2560x1440@60",
		position = "2560x0",
		scale = "1",
	})
end

-- Source: ~/.config/hypr/include/common.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("include.common")
require("../hypremoji/hypremoji")

--exec-once = "sleep 5; hyprctl plugin load /var/cache/hyprpm/fuhry/hyprland-plugins/hyprbars.so"

--plugin load /var/cache/hyprpm/fuhry/virtual-desktops/virtual-desktops.so
--plugin load /var/cache/hyprpm/fuhry/hyprland-plugins/hyprbars.so

-- HyprEmoji config
-- Source: ~/.config/hypremoji/hypremoji.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("hypremoji")

hl.on("hyprland.start", function()
    hl.exec_cmd("\"sleep 5; hyprctl plugin load /var/cache/hyprpm/fuhry/virtual-desktops/virtual-desktops.so\"")
end)

