-- vim: set ts=4 sw=4 noet:

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start wireplumber.service")
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
    hl.exec_cmd("systemctl --user start hyprpaper.service")
    hl.exec_cmd("systemctl --user start hypridle.service")
    hl.exec_cmd("systemctl --user start waybar@top.service")
    hl.exec_cmd("systemctl --user start waybar@bottom.service")
    hl.exec_cmd("/bin/bash -c \"sleep 3; hyprpm reload\"")
end)


