-- vim: set ts=4 sw=4 noet:

--#######################
--##	   HYPREXPO		 ###
--#######################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
	hyprexpo {
		columns = 3
		gap_size = 5
		bg_col = rgb(111111)
		workspace_method = center current
	}
]]

