-- vim: set ts=4 sw=4 noet:

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
	plugin = {
		hyprbars = {
			bar_height = 32,
			bar_color = "rgba(11111180)",
			bar_blur = true,
			bar_text_font = "JetBrains Mono",
			bar_text_align = "left",
			bar_text_size = 9,
			bar_part_of_window = true,
			bar_precedence_over_border = true,
		}
	}
})

hl.plugin.hyprbars.add_button({
	fg_color = "rgb(000000)",
	bg_color = "rgba(ffffffb0)",
	size = 10,
	icon = "×",
	action = "hyprctl dispatch 'hl.dsp.window.close()'",
})

hl.plugin.hyprbars.add_button({
	fg_color = "rgb(000000)",
	bg_color = "rgba(ffffffb0)",
	size = 10,
	icon = "□",
	action = "hyprctl dispatch 'hl.dsp.window.float({ action = \"toggle\" })'",
})

-- windowrule = plugin:hyprbars:bar_color rgb(ff0000), class:^(bluebubbles)

hl.window_rule({
    name = "no-hyprbars-on-tiled-windows",
    match = {
        float = 0,
    },
    ["hyprbars:no_bar"] = true
})

hl.window_rule({
    name = "no-hyprbars-on-vs-code",
    match = {
        initial_title = "Visual Studio Code",
    },
    ["hyprbars:no_bar"] = true
})

-- windowrule = plugin:hyprbars:nobar on,match:float 0
-- windowrule = plugin:hyprbars:nobar on,match:class bluebubbles
