-- vim: set ts=4 sw=4 noet:

--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind("ALT + F4", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind("ALT + F2", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + M", hl.dsp.layout("swapwithmaster"))

hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("/home/fuhry/bin/grimb"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("exaile --prev"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("exaile --play"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("exaile --play-pause"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("exaile --stop"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("exaile --next"))
hl.bind("SUPER + ALT + Q", hl.dsp.exit())
hl.bind("SUPER + ALT + Z", hl.dsp.exec_cmd("systemctl suspend"))

-- TODO: manual review on line 127 — no mapping for dispatcher "nextdesk"
hl.bind("CTRL + ALT + Right", function()
	hl.plugin.virtual_desktops.nextdesk()
end)
hl.bind("CTRL + ALT + Left", function()
	hl.plugin.virtual_desktops.prevdesk()
end)
hl.bind("CTRL + ALT + SHIFT + Right", function()
	hl.plugin.virtual_desktops.movetonextdesk()
end)
hl.bind("CTRL + ALT + SHIFT + Left", function()
	hl.plugin.virtual_desktops.movetoprevdesk()
end)
-- TODO: manual review on line 128 — no mapping for dispatcher "prevdesk"
-- hl.bind("CTRL+ALT + Left", hl.dsp.prevdesk(""))
-- TODO: manual review on line 129 — no mapping for dispatcher "movetonextdesk"
-- hl.bind("CTRL+ALT+SHIFT + Right", hl.dsp.movetonextdesk(""))
-- TODO: manual review on line 130 — no mapping for dispatcher "movetoprevdesk"
-- hl.bind("CTRL+ALT+SHIFT + Left", hl.dsp.movetoprevdesk(""))
hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#gestures
    -- gestures {
    -- 	workspace_swipe = false
    -- }
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    --bind = ALT, F2, exec, $terminal
    --bind = $mainMod, C, killactive,
    -- bind = $mainMod, P, pseudo, # dwindle
    -- bind = $mainMod, J, togglesplit, # dwindle
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- bindm = $mainMod, mouse:272, movewindow
    -- bindm = $mainMod, mouse:273, resizewindow
    -- Laptop multimedia keys for volume and LCD brightness
    -- bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
    -- bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    -- bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    -- bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    -- bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
    -- bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
    -- Requires playerctl
    -- bindl = , XF86AudioNext, exec, playerctl next
    -- bindl = , XF86AudioPause, exec, playerctl play-pause
    -- bindl = , XF86AudioPlay, exec, playerctl play-pause
    -- bindl = , XF86AudioPrev, exec, playerctl previous
    --bind = $mainMod, O, hyprexpo:expo, toggle
    -- vdesk
})

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"))

