-- vim: set ts=4 sw=4 noet:

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    dwindle = {
        --	pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "slave",
        orientation = "center",
        mfact = 0.45,
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

