-- vim: set ts=4 sw=4 noet:

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
-- windowrule = bordersize 0, floating:0, onworkspace:f[1]
-- windowrule = rounding 0, floating:0, onworkspace:f[1]
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "bluebubbles",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "org.telegram.desktop",
    },
    float = true,
})

-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name = "fix-wayland-dragging-issues",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_initial_focus = true,
})

hl.window_rule({
    name = "fix-zoom-annotation-overlay",
    match = {
        class = "^zoom$",
        title = "^annotate_toolbar$",
    },
    no_initial_focus = true,
    float = true,
    ["hyprbars:no_bar"] = true,
    -- TODO: manual review — unrecognized window_rule block field "hyprbars:no_bar"
    -- match:xwayland = 0
    -- match:float = 0
    -- match:fullscreen = 0
    -- match:pin = 0
})

hl.window_rule({
    name = "allow-zoom-to-maximize",
    match = {
        class = "^zoom$",
        title = "^Meeting$",
    },
    -- TODO: manual review — unmapped window rule action: "suppress_event"
})

hl.window_rule({
    name = "fix-zoom-toasts",
    match = {
        class = "^zoom$",
        title = "^zoom$",
    },
    no_initial_focus = true,
    float = true,
})

hl.window_rule({
	name = "no-bar-for-hypremoji",
	match = {
		title = "^HyprEmoji$",
	},
	["hyprbars:no_bar"] = true,
})
