-- vim: set ts=4 sw=4 noet:

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

terminal = "foot"
fileManager = "caja --no-desktop"
menu = "wofi --show drun"

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Nvidia stuff
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- other
hl.env("WALLPAPER_DIR", os.getenv("HOME") .. "/Pictures/Wallpapers")
hl.env("SSH_AUTH_SOCK", "/run/user/" .. system("id -u") .. "/gcr/ssh")
